import crypto from "crypto"
import jwt from "jwt"

const generateToken = ()=>{
    const rawToken = crypto.randomBytes(32).toString("hex")
    const hashedToken = crypto.createHash("sha256").update(rawToken).digest("hex")
    return {rawToken, hashedToken}
}
const generateRefreshToken = (payload)=>{
     jwt.sign(payload, process.env.REFRESH_TOKEN, {
        expiresIn: process.env.REFRESH_TOKEN_EXPIRES_IN || "8d"
     })
}
const verifyRefreshToken = (token)=>{
    jwt.verify(token, process.env.REFRESH_TOKEN)
    //jwt token will be only coming as token which is sent while generation of refreshToken. correct?
    //the generated refreshtoken will be only verified which we have created using jwt. correct?
    //we will verify the same token which was generated by refreshToken. correct?
}

const generateAccessToken = (payload)=>{
    jwt.sign(payload, process.env.ACCESS_TOKEN, {
        expiresIn: process.env.ACCESS_TOKEN_EXPIRES_IN || "2d"
    })
}

const verifyAccessToken = (token)=>{
    jwt.verify(token, process.env.ACCESS_TOKEN) 
}

export {generateToken, generateRefreshToken, verifyRefreshToken, generateAccessToken, verifyAccessToken}

